# Generated by Django 3.1.5 on 2021-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocks',
            options={'ordering': ['id'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterField(
            model_name='blocks',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
